// Generated by tools/arena_manifest.mjs from campaign placement.
export default {
  "2,4": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "5,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "5,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "5,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "5,4": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "8,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "8,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "8,4": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "11,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "11,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "11,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "11,4": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "14,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "14,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "14,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "17,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "17,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "17,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "20,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "20,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "20,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "20,4": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "23,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "23,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "23,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "23,4": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "26,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "26,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "26,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "29,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "29,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "29,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "32,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "32,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "32,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "35,1": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "35,2": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "35,3": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "35,4": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "31,1": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "33,2": {
    "type": "plant",
    "radius": 0.24,
    "height": 0.85,
    "hp": 20
  },
  "12,8": {
    "type": "bigTable",
    "radius": 0.5,
    "height": 0.5,
    "hp": 40
  },
  "14,8": {
    "type": "plant",
    "radius": 0.24,
    "height": 0.85,
    "hp": 20
  },
  "10,7": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "26,6": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "27,6": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "28,6": {
    "type": "plant",
    "radius": 0.24,
    "height": 0.85,
    "hp": 20
  },
  "29,6": {
    "type": "floorLamp",
    "radius": 0.16,
    "height": 1.05,
    "hp": 15
  },
  "30,6": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "24,7": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "25,9": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "26,9": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "27,9": {
    "type": "plant",
    "radius": 0.24,
    "height": 0.85,
    "hp": 20
  },
  "29,9": {
    "type": "floorLamp",
    "radius": 0.16,
    "height": 1.05,
    "hp": 15
  },
  "30,9": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "31,9": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "2,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "2,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "2,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "2,14": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "4,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "4,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "4,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "4,14": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "6,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "6,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "6,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "6,14": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "8,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "8,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "8,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "10,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "10,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "10,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "12,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "12,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "12,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "14,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "14,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "14,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "16,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "16,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "16,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "18,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "18,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "18,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "18,14": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "20,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "20,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "20,14": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "22,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "22,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "22,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "24,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "24,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "24,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "26,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "26,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "26,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "28,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "28,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "28,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "30,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "30,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "30,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "32,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "32,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "32,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "34,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "34,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "34,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "34,14": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "36,11": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "36,12": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "36,13": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "36,14": {
    "type": "desk",
    "radius": 0.42,
    "height": 0.72,
    "hp": 40
  },
  "5,13": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "35,11": {
    "type": "plant",
    "radius": 0.24,
    "height": 0.85,
    "hp": 20
  },
  "8,16": {
    "type": "vending",
    "radius": 0.34,
    "height": 1.25,
    "hp": 80
  },
  "9,16": {
    "type": "counter",
    "radius": 0.45,
    "height": 0.7,
    "hp": 45
  },
  "12,16": {
    "type": "fridge",
    "radius": 0.32,
    "height": 1.1,
    "hp": 70
  },
  "13,16": {
    "type": "cooler",
    "radius": 0.26,
    "height": 0.75,
    "hp": 30
  },
  "14,16": {
    "type": "bench",
    "radius": 0.4,
    "height": 0.6,
    "hp": 35
  },
  "15,16": {
    "type": "vending",
    "radius": 0.34,
    "height": 1.25,
    "hp": 80
  },
  "17,16": {
    "type": "counter",
    "radius": 0.45,
    "height": 0.7,
    "hp": 45
  },
  "18,16": {
    "type": "fridge",
    "radius": 0.32,
    "height": 1.1,
    "hp": 70
  },
  "8,17": {
    "type": "cooler",
    "radius": 0.26,
    "height": 0.75,
    "hp": 30
  },
  "21,16": {
    "type": "shelf",
    "radius": 0.38,
    "height": 1.15,
    "hp": 60
  },
  "22,16": {
    "type": "crate",
    "radius": 0.34,
    "height": 0.6,
    "hp": 30
  },
  "23,16": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "24,16": {
    "type": "shelf",
    "radius": 0.38,
    "height": 1.15,
    "hp": 60
  },
  "25,16": {
    "type": "crate",
    "radius": 0.34,
    "height": 0.6,
    "hp": 30
  },
  "26,16": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "27,16": {
    "type": "shelf",
    "radius": 0.38,
    "height": 1.15,
    "hp": 60
  },
  "29,16": {
    "type": "crate",
    "radius": 0.34,
    "height": 0.6,
    "hp": 30
  },
  "30,16": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "14,21": {
    "type": "copier",
    "radius": 0.34,
    "height": 0.95,
    "hp": 50
  },
  "16,21": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "17,21": {
    "type": "copier",
    "radius": 0.34,
    "height": 0.95,
    "hp": 50
  },
  "18,21": {
    "type": "cooler",
    "radius": 0.26,
    "height": 0.75,
    "hp": 30
  },
  "20,21": {
    "type": "copier",
    "radius": 0.34,
    "height": 0.95,
    "hp": 50
  },
  "28,21": {
    "type": "copier",
    "radius": 0.34,
    "height": 0.95,
    "hp": 50
  },
  "29,21": {
    "type": "cooler",
    "radius": 0.26,
    "height": 0.75,
    "hp": 30
  },
  "30,21": {
    "type": "copier",
    "radius": 0.34,
    "height": 0.95,
    "hp": 50
  },
  "31,21": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "5,23": {
    "type": "copier",
    "radius": 0.34,
    "height": 0.95,
    "hp": 50
  },
  "13,23": {
    "type": "cooler",
    "radius": 0.26,
    "height": 0.75,
    "hp": 30
  },
  "14,23": {
    "type": "copier",
    "radius": 0.34,
    "height": 0.95,
    "hp": 50
  },
  "31,23": {
    "type": "copier",
    "radius": 0.34,
    "height": 0.95,
    "hp": 50
  },
  "33,23": {
    "type": "cooler",
    "radius": 0.26,
    "height": 0.75,
    "hp": 30
  },
  "4,19": {
    "type": "plant",
    "radius": 0.24,
    "height": 0.85,
    "hp": 20
  },
  "2,6": {
    "type": "plant",
    "radius": 0.24,
    "height": 0.85,
    "hp": 20
  },
  "14,19": {
    "type": "plant",
    "radius": 0.24,
    "height": 0.85,
    "hp": 20
  },
  "28,1": {
    "type": "cooler",
    "radius": 0.26,
    "height": 0.75,
    "hp": 30
  },
  "3,4": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  },
  "18,6": {
    "type": "cabinet",
    "radius": 0.32,
    "height": 0.9,
    "hp": 60
  }
};
