// Replay campaign placement without renderer, textures, or a browser.
import * as THREE from 'three';
import { register } from 'node:module';
register('./arena_manifest_loader.mjs', import.meta.url);
const { World } = await import('../src/world.js');
import { LEVELS } from '../src/levels.js';
import { CELL } from '../src/config.js';
import { writeFileSync } from 'node:fs';
class PlacementWorld extends World {
 build() {
  const walls = {'#':CELL.BRICK,W:CELL.WOOD,B:CELL.STONE,C:CELL.CONCRETE,O:CELL.OFFICE,M:CELL.METAL};
  this.w=Math.max(...this.level.map.map(r=>r.length)); this.h=this.level.map.length;
  this.grid=new Int8Array(this.w*this.h);
  this.level.map.forEach((row,y)=>[...row].forEach((ch,x)=>{
   let type=walls[ch]??CELL.EMPTY;
   if(ch==='+') type=CELL.DOOR;
   else if(ch==='X') type=CELL.GATE;
   else if(ch==='E') type=CELL.ELEVATOR;
   else if(ch==='S') this.spawn={x:x+.5,y:y+.5};
   else if(walls[ch]===undefined && ch!=='.' && ch!==' ') {this.entities.push({char:ch,x:x+.5,y:y+.5});if(ch==='T')this.objectiveCells.add(this.key(x,y));}
   this.grid[y*this.w+x]=type;
  }));
  this._sx=Math.floor(this.spawn.x);this._sy=Math.floor(this.spawn.y);
  this._occupied=new Set(this.entities.map(e=>this.key(Math.floor(e.x),Math.floor(e.y))));
  this._reachable=this.floodCount();this.addZones();this.addProps();
 }
}
const world=new PlacementWorld(new THREE.Scene(),LEVELS[1],1);
const props=Object.fromEntries([...world.props].map(([id,p])=>[id,{type:p.type,radius:p.def.radius,height:p.def.height,hp:p.def.hp}]));
writeFileSync(new URL('../shared/arena/office-props.js',import.meta.url),'// Generated by tools/arena_manifest.mjs from campaign placement.\nexport default '+JSON.stringify(props,null,2)+';\n');
console.log(`Exported ${world.props.size} campaign prop footprints`);
