/**
 * LEVEL DEFINITIONS
 * Map legend:
 *   walls: '#' brick, 'W' wood, 'B' stone, 'M' metal, 'O' office panel, 'C' concrete
 *   '+' door, 'X' elevator gate (locked until all tables), 'E' elevator pad
 *   'S' player start, 'T' table (objective)
 *   enemies: 'g' guard, 'm' manager, 'x' executive, 'D' mixed/random, 'G' BOSS
 *   pickups: 'A' ammo, 'H' health, '$' money, 'Z' gold bar,
 *            'L' table-leg weapon, 'P' paint-sprayer weapon
 */

export const LEVELS = [
    // ---------------------------------------------------------------- LEVEL 1
    {
        name: 'The Lobby',
        subtitle: 'Ground floor. Smile for the receptionist.',
        wallChar: 'O',
        floorTex: 'marble', ceilTex: 'ceiling',
        fogColor: 0x303440, fogDensity: 0.055,
        ambient: 0x8890a8, ambientIntensity: 1.15,
        accent: 0xffd9a0,
        music: 'lobby',
        // Design: corporate ground floor. Reception counters greet you, security
        // booths flank the hall, a waiting lounge faces them; behind the wall sit
        // the staff lounge, break room (snacks!) and a manager's office, with a
        // security checkpoint guarding the elevator.
        zones: [
            { rect: [2, 1, 28, 2], kind: 'garden', density: 0.18, rug: false }, // entry planters
            { rect: [9, 4, 10, 3], kind: 'reception' },
            { rect: [2, 8, 28, 2], kind: 'lounge', density: 0.3, rug: false },
            { rect: [2, 11, 8, 4], kind: 'lounge' },
            { rect: [12, 11, 8, 4], kind: 'breakroom' },
            { rect: [23, 11, 7, 4], kind: 'managerOffice' },
            { rect: [2, 16, 28, 3], kind: 'security', density: 0.22 },
        ],
        props: { plant: 3, cooler: 1 },
        decor: { paintings: 8, rugs: 2, rugColor: 0x7a2a22 },
        map: [
            "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
            "OS.............................O",
            "O...........$..................O",
            "O...WWWW............WWWW.......O",
            "O...W..W............W..W.......O",
            "O...W..+.....g......+..W.......O",
            "O...W..W............W..W.......O",
            "O...WWWW............WWWW.......O",
            "O..............................O",
            "O.....$.......g.........$......O",
            "OOOOOO+OOOOOOOOOOOOOOOOOO+OOOOOO",
            "O.........O..........O.........O",
            "O....T....O....H.....O....T....O",
            "O....g....O..........O....g....O",
            "O.........O....A.....O.........O",
            "OOOOOOOOO.OOOOO..OOOO.OOOOOOOOOO",
            "O..............................O",
            "O...H...g.....$..$.....g....A..O",
            "O..............................O",
            "OOOOOOOOOOOOOOOXXOOOOOOOOOOOOOOO",
            "O..............EE..............O",
            "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 2
    {
        name: 'The Office',
        subtitle: 'Cubicle farm. The guards are unionized.',
        wallChar: 'O',
        floorTex: 'carpet', ceilTex: 'ceiling',
        fogColor: 0x2a2a30, fogDensity: 0.06,
        ambient: 0x9090a0, ambientIntensity: 1.0,
        accent: 0xfff2cc,
        music: 'office',
        // Design: a working floor. Open-plan desks at the entry, a conference
        // room and the manager's office up top, the dense cubicle farm in the
        // middle, then the break room and supply room (grab the nail gun there).
        zones: [
            { rect: [2, 1, 36, 4], kind: 'cubicles', gap: 3 },
            { rect: [8, 6, 8, 4], kind: 'conference' },
            { rect: [24, 6, 8, 4], kind: 'managerOffice' },
            { rect: [2, 11, 36, 4], kind: 'cubicles' },
            { rect: [8, 16, 11, 3], kind: 'breakroom' },
            { rect: [21, 16, 11, 3], kind: 'supply' },
            { rect: [2, 21, 36, 3], kind: 'copyRoom' }, // print row by the elevator
        ],
        props: { plant: 3, cooler: 1, cabinet: 2 },
        decor: { paintings: 5, rugs: 2, rugColor: 0x33455e },
        map: [
            "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
            "OS......$..............................O",
            "O..............................H.......O",
            "O..A................................$..O",
            "O.................Z....................O",
            "O......WWWWWWWWWW......WWWWWWWWWW......O",
            "O......W........W......W........W......O",
            "O......W...T..$.W......W.$..T...W......O",
            "O......W........W......W........W......O",
            "O......W...g....+......+....g...W......O",
            "O......WWWWWWWWWW......WWWWWWWWWW......O",
            "O......................................O",
            "O..g.......m.......L.......m.......g...O",
            "O..........$........Z........$........O",
            "O......................................O",
            "O......WWWWWWWWWWWWWWWWWWWWWWWWWW......O",
            "O......W..H.....................W......O",
            "O......W.......T....m.....Z.N...W......O",
            "O......W........................W......O",
            "O......+........................+......O",
            "O......WWWWWWWWWWWWWWWWWWWWWWWWWW......O",
            "O...........m..............x...........O",
            "O..H.......A.......H.......A.......H...O",
            "O..........$........................$..O",
            "OOOOOOOOOOOOOOOOOOXXOOOOOOOOOOOOOOOOOOOO",
            "O.................EE...................O",
            "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 3
    {
        name: 'The Archives',
        subtitle: 'Where they bury the warranty claims.',
        wallChar: 'B',
        floorTex: 'stoneFloor', ceilTex: 'stoneFloor',
        fogColor: 0x12131c, fogDensity: 0.085,
        ambient: 0x556070, ambientIntensity: 0.85,
        accent: 0xff9944,
        music: 'archives',
        // Design: the records basement. Locked records vaults on the flanks,
        // long shelf stacks through the middle, reading rooms with banquet
        // tables (the nail gun got misfiled in one), and a supply corridor.
        zones: [
            { rect: [4, 3, 6, 4], kind: 'vault' },
            { rect: [14, 3, 13, 4], kind: 'aisles' },
            { rect: [31, 3, 6, 4], kind: 'vault' },
            { rect: [2, 8, 37, 3], kind: 'supply', density: 0.12 }, // cart corridor
            { rect: [10, 12, 14, 5], kind: 'readingRoom' },
            { rect: [26, 12, 12, 5], kind: 'aisles' },
            { rect: [2, 18, 37, 3], kind: 'supply', density: 0.18 },
            { rect: [9, 22, 21, 4], kind: 'readingRoom' },
            { rect: [2, 22, 5, 4], kind: 'vault' },   // overflow records
            { rect: [33, 22, 6, 4], kind: 'vault' },
        ],
        props: { crate: 4, cabinet: 2 },
        decor: { paintings: 2 },
        map: [
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BS..........$......A................$..B",
            "B..BBBBBBBB..BBBBBBBBBBBBBBB..BBBBBBB..B",
            "B..B.......B.B..............B.B......B.B",
            "B..B..T....B.B......$.......B.B..H.Z..B.B",
            "B..B..g....+.+..............+.+......B.B",
            "B..B..$....B.B..............B.B......B.B",
            "B..BBBBBBBB..BBBBBB+BBBBBBBB..BBBBBB..B.B",
            "B......................................B",
            "B..H...........$..............g....Z..B",
            "B......................................B",
            "BBBBB+BBBBBBBBBBBBBBBBBBBBBBBBBB+BBBBBBB",
            "B..$....B...............B............$.B",
            "B..m....B.......T.N.....B.......m......B",
            "B.......B.......g.......B..............B",
            "B.......+...............+..............B",
            "B.......B.......Z.......B..............B",
            "BBBBBBBBB...BBBBBBBBBBB...BBBBBBBBBBBBBB",
            "B......................................B",
            "B..A.......A..$....A.......A.......A...B",
            "B......................................B",
            "BBBBB..BBBBBBBBBBBBBBBBBBBBBBBB..BBBBBBB",
            "B..$...B.......................B...$...B",
            "B..m...B...........T...........B...m...B",
            "B......+.......................+.......B",
            "B......B..........g............B.......B",
            "BBBBBBBBBBBBBBBBB..BBBBBBBBBBBBBBBBBBBBB",
            "B................XX....................B",
            "B................EE....................B",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 4
    {
        name: 'The Showroom',
        subtitle: 'Fast furniture as far as the eye can see.',
        wallChar: 'W',
        floorTex: 'woodFloor', ceilTex: 'ceiling',
        fogColor: 0x2c2218, fogDensity: 0.06,
        ambient: 0xb09878, ambientIntensity: 1.0,
        accent: 0xffe0b0,
        music: 'showroom',
        // Design: fast-furniture retail. Display pods up front with staged
        // living-room vignettes between them, the warehouse flat-pack aisles
        // in the middle (roller launcher fell off a pallet), vignette gallery
        // to the right, checkout lanes before the elevator.
        zones: [
            { rect: [9, 3, 5, 4], kind: 'vignette' },
            { rect: [20, 3, 5, 4], kind: 'vignette' },
            { rect: [31, 3, 7, 4], kind: 'vignette' },
            { rect: [2, 8, 36, 3], kind: 'lounge', density: 0.2, rug: false },
            { rect: [2, 12, 22, 6], kind: 'flatpack' },
            { rect: [27, 12, 12, 6], kind: 'vignette', count: 6 },
            { rect: [4, 19, 32, 2], kind: 'gallery', props: ['plant'], step: 4, accents: [] }, // queue planters
            { rect: [4, 21, 32, 2], kind: 'checkout' },
        ],
        props: { plant: 2, bench: 2 },
        decor: { paintings: 6, rugs: 3, rugColor: 0x8a4a26 },
        map: [
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "WS.....$...............................W",
            "W..........g...............m..........W",
            "W...CCCC.......CCCC.......CCCC.........W",
            "W...C..C.......C..C.......C..C.....H...W",
            "W...C.TC.......C.$C.......CT.C.........W",
            "W...C..C.......C..C.......C..C.........W",
            "W...CC+C.......CC+C.......CC+C.........W",
            "W......................................W",
            "W..H........x.........Z.......g.....A..W",
            "W......................................W",
            "WWWWWW+WWWWWWWWWWWWWWWWWWWWWWWWW+WWWWWWW",
            "W.......................W.............W",
            "W..$........T...........W....m....$...W",
            "W.....R......m..........W.............W",
            "W........................+............W",
            "W..g.....................W......Z.....W",
            "W.........Z..............W............W",
            "WWWWWWWWWW+WWWWWWWWWWWWWWWWWWWW+WWWWWWWW",
            "W............x..........m..............W",
            "W...A....g.......T..........x......H...W",
            "W..............$...$...................W",
            "W......................................W",
            "WWWWWWWWWWWWWWWWWWWXXWWWWWWWWWWWWWWWWWWW",
            "W..................EE..................W",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 5
    {
        name: 'The Factory',
        subtitle: 'Where masterpieces become particle board.',
        wallChar: 'M',
        floorTex: 'factoryFloor', ceilTex: 'metalCeil',
        fogColor: 0x101418, fogDensity: 0.07,
        ambient: 0x607080, ambientIntensity: 0.9,
        accent: 0x88ddff,
        music: 'factory',
        // Design: the particle-board plant. Receiving dock up top, the main
        // assembly line of machines across the second band, paint stock and
        // the lumber yard in the middle, shipping dock by the freight elevator.
        zones: [
            { rect: [3, 1, 42, 4], kind: 'dock' },
            { rect: [3, 7, 42, 3], kind: 'assembly' },
            { rect: [4, 12, 18, 5], kind: 'paintstock' },
            { rect: [26, 12, 18, 5], kind: 'lumberyard' },
            { rect: [4, 19, 16, 5], kind: 'lumberyard' },
            { rect: [26, 19, 18, 5], kind: 'dock', count: 8 },
        ],
        props: { crate: 3, barrel: 3, machine: 1 },
        map: [
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MS.....T.......................................M",
            "M..............................................M",
            "M..H.......A........$..........................M",
            "M.....................Z........................M",
            "MMMMMM+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+MMMMMMMMM",
            "M.......................P......................M",
            "M..g...m...g...x...g...m...g...x...g...m...g...M",
            "M..........$........Z........$.....T...........M",
            "M..A.......H.......A.......H.......A.......H...M",
            "M..............................................M",
            "MMMMMM+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+MMMMMMMMM",
            "M..............................................M",
            "M..A.......A....x.......x..........A.......A...M",
            "M..............................................M",
            "M..H.......H..$....H.......H.......H.......H...M",
            "M..............................................M",
            "MMMMMM+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+MMMMMMMMM",
            "M..............................................M",
            "M..........$........Z........$.....T...........M",
            "M..A.......H...x...A...m...H.......A.......H...M",
            "M..............................................M",
            "M..H.......H..$....H.......H.......H.......H...M",
            "M..A.......A.......A.......A.......A...T...A...M",
            "M..............................................M",
            "MMMMMMMMMMMMMMMMMMMMM..MMMMMMMMMMMMMMMMMMMMMMMMM",
            "M...................XX.........................M",
            "M...................EE.........................M",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 6
    {
        name: 'The Penthouse',
        subtitle: 'The Head Designer will see you now.',
        wallChar: 'M',
        floorTex: 'marble', ceilTex: 'metalCeil',
        fogColor: 0x1a0808, fogDensity: 0.055,
        ambient: 0x806060, ambientIntensity: 0.9,
        accent: 0xff5533,
        music: 'boss',
        boss: true,
        // Design: the Head Designer's penthouse. A statue gallery antechamber
        // (golden tables on plinths — his trophies), then the duel arena ringed
        // with executive garden corners. The center stays open for the fight.
        zones: [
            { rect: [2, 1, 28, 5], kind: 'gallery' },
            { rect: [2, 8, 6, 5], kind: 'garden' },
            { rect: [24, 8, 6, 5], kind: 'garden' },
            { rect: [2, 16, 6, 5], kind: 'garden' },
            { rect: [24, 16, 6, 5], kind: 'garden' },
        ],
        props: { plant: 2 },
        decor: { paintings: 6, rugs: 2, rugColor: 0x5a1430 },
        map: [
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MS......A.......H.......A......M",
            "M..............................M",
            "M....H......$........$......H..M",
            "M..............................M",
            "M.....A.......Z........A.......M",
            "M..............................M",
            "MMMMMMMMMMMMMM+MMMMMMMMMMMMMMMMM",
            "M..............................M",
            "M..Z........................Z..M",
            "M......CC............CC........M",
            "M......CC.H........A.CC........M",
            "M...A......................A...M",
            "M....A.........................M",
            "M..............G...............M",
            "M.........................A....M",
            "M......H................H......M",
            "M......CC.A........H.CC........M",
            "M......CC............CC........M",
            "M..H........................A..M",
            "M..............................M",
            "M..Z..........................ZM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        ],
    },
];
