/**
 * LEVEL DEFINITIONS
 * Map legend:
 *   walls: '#' brick, 'W' wood, 'B' stone, 'M' metal, 'O' office panel, 'C' concrete
 *   '+' door, 'X' elevator gate (locked until all tables), 'E' elevator pad
 *   'S' player start, 'T' table (objective)
 *   enemies: 'g' guard, 'm' manager, 'x' executive, 'D' mixed/random, 'G' BOSS
 *   pickups: 'A' ammo, 'H' health, '$' money, 'Z' gold bar,
 *            'L' table-leg weapon, 'P' paint-sprayer weapon
 */

export const LEVELS = [
    // ---------------------------------------------------------------- LEVEL 1
    {
        name: 'The Lobby',
        subtitle: 'Ground floor. Smile for the receptionist.',
        wallChar: 'O',
        floorTex: 'marble', ceilTex: 'ceiling',
        fogColor: 0x303440, fogDensity: 0.055,
        ambient: 0x8890a8, ambientIntensity: 1.15,
        accent: 0xffd9a0,
        music: 'lobby',
        map: [
            "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
            "OS.............................O",
            "O...........$..................O",
            "O...WWWW............WWWW.......O",
            "O...W..W............W..W.......O",
            "O...W..+.....g......+..W.......O",
            "O...W..W............W..W.......O",
            "O...WWWW............WWWW.......O",
            "O..............................O",
            "O.....$.......g.........$......O",
            "OOOOOO+OOOOOOOOOOOOOOOOOO+OOOOOO",
            "O.........O..........O.........O",
            "O....T....O....H.....O....T....O",
            "O....g....O..........O....g....O",
            "O.........O....A.....O.........O",
            "OOOOOOOOO.OOOOO..OOOO.OOOOOOOOOO",
            "O..............................O",
            "O...H...g.....$..$.....g....A..O",
            "O..............................O",
            "OOOOOOOOOOOOOOOXXOOOOOOOOOOOOOOO",
            "O..............EE..............O",
            "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 2
    {
        name: 'The Office',
        subtitle: 'Cubicle farm. The guards are unionized.',
        wallChar: 'O',
        floorTex: 'carpet', ceilTex: 'ceiling',
        fogColor: 0x2a2a30, fogDensity: 0.06,
        ambient: 0x9090a0, ambientIntensity: 1.0,
        accent: 0xfff2cc,
        music: 'office',
        map: [
            "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
            "OS......$..............................O",
            "O..............................H.......O",
            "O..A................................$..O",
            "O.................Z....................O",
            "O......WWWWWWWWWW......WWWWWWWWWW......O",
            "O......W........W......W........W......O",
            "O......W...T..$.W......W.$..T...W......O",
            "O......W........W......W........W......O",
            "O......W...g....+......+....g...W......O",
            "O......WWWWWWWWWW......WWWWWWWWWW......O",
            "O......................................O",
            "O..g.......m.......L.......m.......g...O",
            "O..........$........Z........$........O",
            "O......................................O",
            "O......WWWWWWWWWWWWWWWWWWWWWWWWWW......O",
            "O......W........................W......O",
            "O......W.......T....m.....Z.....W......O",
            "O......W........................W......O",
            "O......+........................+......O",
            "O......WWWWWWWWWWWWWWWWWWWWWWWWWW......O",
            "O...........m..............x...........O",
            "O..H.......A.......H.......A.......H...O",
            "O..........$........................$..O",
            "OOOOOOOOOOOOOOOOOOXXOOOOOOOOOOOOOOOOOOOO",
            "O.................EE...................O",
            "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 3
    {
        name: 'The Archives',
        subtitle: 'Where they bury the warranty claims.',
        wallChar: 'B',
        floorTex: 'stoneFloor', ceilTex: 'stoneFloor',
        fogColor: 0x12131c, fogDensity: 0.085,
        ambient: 0x556070, ambientIntensity: 0.85,
        accent: 0xff9944,
        music: 'archives',
        map: [
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BS..........$......A................$..B",
            "B..BBBBBBBB..BBBBBBBBBBBBBBB..BBBBBBB..B",
            "B..B.......B.B..............B.B......B.B",
            "B..B..T....B.B......$.......B.B..H.Z..B.B",
            "B..B..g....+.+..............+.+......B.B",
            "B..B..$....B.B..............B.B......B.B",
            "B..BBBBBBBB..BBBBBB+BBBBBBBB..BBBBBB..B.B",
            "B......................................B",
            "B..H...........$..............g....Z..B",
            "B......................................B",
            "BBBBB+BBBBBBBBBBBBBBBBBBBBBBBBBB+BBBBBBB",
            "B..$....B...............B............$.B",
            "B..m....B.......T.......B.......m......B",
            "B.......B.......g.......B..............B",
            "B.......+...............+..............B",
            "B.......B.......Z.......B..............B",
            "BBBBBBBBB...BBBBBBBBBBB...BBBBBBBBBBBBBB",
            "B......................................B",
            "B..A.......A..$....A.......A.......A...B",
            "B......................................B",
            "BBBBB..BBBBBBBBBBBBBBBBBBBBBBBB..BBBBBBB",
            "B..$...B.......................B...$...B",
            "B..m...B...........T...........B...m...B",
            "B......+.......................+.......B",
            "B......B..........g............B.......B",
            "BBBBBBBBBBBBBBBBB..BBBBBBBBBBBBBBBBBBBBB",
            "B................XX....................B",
            "B................EE....................B",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 4
    {
        name: 'The Showroom',
        subtitle: 'Fast furniture as far as the eye can see.',
        wallChar: 'W',
        floorTex: 'woodFloor', ceilTex: 'ceiling',
        fogColor: 0x2c2218, fogDensity: 0.06,
        ambient: 0xb09878, ambientIntensity: 1.0,
        accent: 0xffe0b0,
        music: 'showroom',
        map: [
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "WS.....$...............................W",
            "W..........g...............m..........W",
            "W...CCCC.......CCCC.......CCCC.........W",
            "W...C..C.......C..C.......C..C.....H...W",
            "W...C.TC.......C.$C.......CT.C.........W",
            "W...C..C.......C..C.......C..C.........W",
            "W...CC+C.......CC+C.......CC+C.........W",
            "W......................................W",
            "W..H........x.........Z.......g.....A..W",
            "W......................................W",
            "WWWWWW+WWWWWWWWWWWWWWWWWWWWWWWWW+WWWWWWW",
            "W.......................W.............W",
            "W..$........T...........W....m....$...W",
            "W............m..........W.............W",
            "W........................+............W",
            "W..g.....................W......Z.....W",
            "W.........Z..............W............W",
            "WWWWWWWWWW+WWWWWWWWWWWWWWWWWWWW+WWWWWWWW",
            "W............x..........m..............W",
            "W...A....g.......T..........x......H...W",
            "W..............$...$...................W",
            "W......................................W",
            "WWWWWWWWWWWWWWWWWWWXXWWWWWWWWWWWWWWWWWWW",
            "W..................EE..................W",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 5
    {
        name: 'The Factory',
        subtitle: 'Where masterpieces become particle board.',
        wallChar: 'M',
        floorTex: 'factoryFloor', ceilTex: 'metalCeil',
        fogColor: 0x101418, fogDensity: 0.07,
        ambient: 0x607080, ambientIntensity: 0.9,
        accent: 0x88ddff,
        music: 'factory',
        map: [
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MS.....T.......................................M",
            "M..............................................M",
            "M..H.......A........$..........................M",
            "M.....................Z........................M",
            "MMMMMM+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+MMMMMMMMM",
            "M.......................P......................M",
            "M..g...m...g...x...g...m...g...x...g...m...g...M",
            "M..........$........Z........$.....T...........M",
            "M..A.......H.......A.......H.......A.......H...M",
            "M..............................................M",
            "MMMMMM+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+MMMMMMMMM",
            "M..............................................M",
            "M..A.......A....x.......x..........A.......A...M",
            "M..............................................M",
            "M..H.......H..$....H.......H.......H.......H...M",
            "M..............................................M",
            "MMMMMM+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+MMMMMMMMM",
            "M..............................................M",
            "M..........$........Z........$.....T...........M",
            "M..A.......H...x...A...m...H.......A.......H...M",
            "M..............................................M",
            "M..H.......H..$....H.......H.......H.......H...M",
            "M..A.......A.......A.......A.......A...T...A...M",
            "M..............................................M",
            "MMMMMMMMMMMMMMMMMMMMM..MMMMMMMMMMMMMMMMMMMMMMMMM",
            "M...................XX.........................M",
            "M...................EE.........................M",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        ],
    },
    // ---------------------------------------------------------------- LEVEL 6
    {
        name: 'The Penthouse',
        subtitle: 'The Head Designer will see you now.',
        wallChar: 'M',
        floorTex: 'marble', ceilTex: 'metalCeil',
        fogColor: 0x1a0808, fogDensity: 0.055,
        ambient: 0x806060, ambientIntensity: 0.9,
        accent: 0xff5533,
        music: 'boss',
        boss: true,
        map: [
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MS......A.......H.......A......M",
            "M..............................M",
            "M....H......$........$......H..M",
            "M..............................M",
            "M.....A.......Z........A.......M",
            "M..............................M",
            "MMMMMMMMMMMMMM+MMMMMMMMMMMMMMMMM",
            "M..............................M",
            "M..Z........................Z..M",
            "M......CC............CC........M",
            "M......CC.H........A.CC........M",
            "M...A......................A...M",
            "M..............................M",
            "M..............G...............M",
            "M..............................M",
            "M......H................H......M",
            "M......CC.A........H.CC........M",
            "M......CC............CC........M",
            "M..H........................A..M",
            "M..............................M",
            "M..Z..........................ZM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        ],
    },
];
